# Generated by Django 2.0.7 on 2018-07-15 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180714_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_date', models.DateTimeField(verbose_name='date voted')),
                ('ip_address', models.GenericIPAddressField()),
                ('vote_detail', models.CharField(max_length=500)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'radio'), (2, 'checkbox'), (3, 'text')], default=1),
        ),
    ]
