# Generated by Django 2.0.7 on 2018-07-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180715_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='pub_date',
            field=models.DateTimeField(db_index=True, verbose_name='date published'),
        ),
    ]
